# Site
repository: elianajn/website
# favicon: images/favicon.ico

# Personal info
name: Eliana Neurohr
title: Computer Science Student
email: elianajneu@gmail.com
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: facespics
#github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: eliana.jn
#linkedin_username: jameswgrant
linkedin_username: elianajn
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name's Eliana, though I often go by Ella, and I'm a computer science student based out of Chicago and Colorado Springs. I'm a second year student at Colorado College, but have been into coding for a good chunk of my life.
#  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Education Section
educaton_title: Education

# Experience Section
experience_title: Experience

#Projects Section
projects_title: Technical Skills


# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in computer science I love doing outdoor sports, including (but definitely not limited to!)
    * Cycling, with two national podium finishes and ten State/Regional Championships (Cyclocross, Track, Road, and Regional Track)
    * Skiing
    * Climbing

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
