# Site
repository: elianajn/website
# favicon: images/favicon.ico

# Personal info
name: Eliana Neurohr
# title: Computer Science Student
email: elianajneu@gmail.com
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: facespics
github_username:  elianajn
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: eliana.jn
#linkedin_username: jameswgrant
linkedin_username: elianajn
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll


# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Eliana, though I often go by Ella, and I'm a computer science student from Chicago and based out of Colorado Springs.
  I'm a fourth year student at Colorado College, but have been coding for a good chunk of my life.
#  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Education Section
educaton_title: Education

# Experience Section
experience_title: Experience

#Projects Section
projects_title: Projects


# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in computer science I love doing outdoor sports, including cycling (with two national podium finishes and ten State/Regional Championships in Cyclocross, Track, and Road),
  climbing, skiing, and hiking. During summer 2020 I lived in my car (Gloria the '05 WRX below) and tooled around Colorado, camping and hiking wherever I could, and taking a shower whenever I had the opportunity (I will admit, an embarrassing number of them were in Boulder Creek).

  I also enjoy textile crafting, such as sewing, crocheting, and cross stitching. I recently crocheted a chalk bag, and have had some of my cross stitching work
  displayed in the Chicago Cultural Center. I consider music and dancing to be life's greatest joys, and always dance like no one is watching.

  nut
more_img_1: images/img_1.jpg
more_img_2: images/img_2.jpg
more_img_3: images/img_3.jpg
more_img_4: images/img_4.jpg

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
